import { log } from "./log";

export interface Issue {
  title: string;
  body: string;
  labels: string;
}

export function fetchIssue(repo: string, issueNum: string): Issue {
  log.info(`Fetching issue #${issueNum} from ${repo}...`);

  const proc = Bun.spawnSync([
    "gh", "issue", "view", issueNum,
    "--repo", repo,
    "--json", "title,body,labels",
  ]);

  if (proc.exitCode !== 0) {
    log.die(`Failed to fetch issue #${issueNum}. Check repo name and issue number.`);
  }

  const json = JSON.parse(proc.stdout.toString());

  return {
    title: json.title,
    body: json.body || "No description provided.",
    labels: json.labels?.map((l: { name: string }) => l.name).join(", ") || "none",
  };
}

export function listIssues(repo: string, verbose: boolean): void {
  log.info(`Fetching open issues for ${repo}...`);

  const fields = verbose
    ? "number,title,body,labels,assignees"
    : "number,title";

  const proc = Bun.spawnSync([
    "gh", "issue", "list",
    "--repo", repo,
    "--state", "open",
    "--json", fields,
  ]);

  if (proc.exitCode !== 0) {
    log.die(`Failed to fetch issues for ${repo}. Check the repo name.`);
  }

  const issues = JSON.parse(proc.stdout.toString());

  if (issues.length === 0) {
    log.info("No open issues found.");
    return;
  }

  log.ok(`${issues.length} open issue(s):\n`);

  for (const issue of issues) {
    if (verbose) {
      const labels = issue.labels?.map((l: { name: string }) => l.name).join(", ") || "none";
      const assignees = issue.assignees?.map((a: { login: string }) => a.login).join(", ") || "unassigned";
      console.log(`  #${issue.number}  ${issue.title}`);
      console.log(`         Labels: ${labels}`);
      console.log(`         Assignees: ${assignees}`);
      console.log(`         ${(issue.body || "No description.").split("\n")[0]}`);
      console.log();
    } else {
      console.log(`  #${issue.number}  ${issue.title}`);
    }
  }
}

export function pushAndCreatePR(
  repo: string,
  worktreeDir: string,
  branchName: string,
  defaultBranch: string,
  issueNum: string,
  issue: Issue,
  summary?: string
): void {
  // Check for unpushed commits or uncommitted changes
  const unpushed = Bun.spawnSync(["git", "log", `origin/${defaultBranch}..HEAD`, "--oneline"], { cwd: worktreeDir });
  const diffCheck = Bun.spawnSync(["git", "diff", "--quiet"], { cwd: worktreeDir });
  const cachedCheck = Bun.spawnSync(["git", "diff", "--cached", "--quiet"], { cwd: worktreeDir });

  const hasUnpushed = unpushed.stdout.toString().trim().length > 0;
  const hasUncommitted = diffCheck.exitCode !== 0 || cachedCheck.exitCode !== 0;

  if (!hasUnpushed && !hasUncommitted) {
    log.warn("No changes detected. Claude may not have made any modifications.");
    log.warn(`Worktree: ${worktreeDir}`);
    return;
  }

  // Stage any unstaged changes Claude might have left
  if (hasUncommitted) {
    log.info("Staging uncommitted changes...");
    const addResult = Bun.spawnSync(["git", "add", "-A"], { cwd: worktreeDir });
    if (addResult.exitCode !== 0) {
      log.die("Failed to stage changes.");
    }
    const prefix = issue.labels.includes("enhancement") || issue.labels.includes("feature") ? "feat" : "fix";
    const commitResult = Bun.spawnSync(["git", "commit", "-m", `${prefix}: address issue #${issueNum} - ${issue.title}`], { cwd: worktreeDir });
    if (commitResult.exitCode !== 0) {
      log.warn("Commit failed — changes may already be committed.");
    }
  }

  // Squash all commits into one
  const commitCount = Bun.spawnSync(["git", "rev-list", "--count", `${defaultBranch}..HEAD`], { cwd: worktreeDir });
  const count = parseInt(commitCount.stdout.toString().trim(), 10) || 0;
  if (count > 1) {
    log.info(`Squashing ${count} commits into one...`);
    const prefix = issue.labels.includes("enhancement") || issue.labels.includes("feature") ? "feat" : "fix";
    const squash = Bun.spawnSync(["git", "reset", "--soft", defaultBranch], { cwd: worktreeDir });
    if (squash.exitCode === 0) {
      const msg = `${prefix}: ${issue.title} (#${issueNum})`;
      Bun.spawnSync(["git", "commit", "-m", msg], { cwd: worktreeDir });
      log.ok("Commits squashed.");
    } else {
      log.warn("Failed to squash — pushing individual commits instead.");
    }
  }

  // Push
  log.info(`Pushing branch '${branchName}' to origin...`);
  const push = Bun.spawnSync(["git", "push", "-u", "origin", branchName], { cwd: worktreeDir });
  if (push.exitCode !== 0) {
    log.die("Failed to push. Check your git credentials.");
  }
  log.ok("Branch pushed.");

  // Create PR
  log.info("Opening pull request...");

  const summarySection = summary
    ? `### What was done\n\n${summary}\n\n`
    : "";

  const prBody = `## Summary

Closes #${issueNum}

${summarySection}This PR was generated by [mog](https://github.com/bobbyg603/mog) using Claude Code in a Docker sandbox.

### Issue: ${issue.title}

${issue.body}

---
*Please review the changes carefully before merging.*`;

  const prefix = issue.labels.includes("enhancement") || issue.labels.includes("feature") ? "feat" : "fix";
  const prTitle = `${prefix}: ${issue.title} [#${issueNum}]`;

  const pr = Bun.spawnSync([
    "gh", "pr", "create",
    "--repo", repo,
    "--base", defaultBranch,
    "--head", branchName,
    "--title", prTitle,
    "--body", prBody,
  ], { cwd: worktreeDir });

  if (pr.exitCode !== 0) {
    log.die("Failed to create PR. You may need to push first or the PR may already exist.");
  }

  const prUrl = pr.stdout.toString().trim();
  log.ok("Pull request created!");
  console.log(`\x1b[0;32m${prUrl}\x1b[0m`);

  console.log();
  log.ok(`All done! Issue #${issueNum} → Branch '${branchName}' → PR opened.`);
  log.info(`Worktree: ${worktreeDir}`);
  log.info(`To clean up the worktree later: git worktree remove ${worktreeDir}`);
}
