import { log } from "./log";

export interface Issue {
  title: string;
  body: string;
  labels: string;
}

export async function fetchIssue(repo: string, issueNum: string): Promise<Issue> {
  log.info(`Fetching issue #${issueNum} from ${repo}...`);

  const proc = Bun.spawnSync([
    "gh", "issue", "view", issueNum,
    "--repo", repo,
    "--json", "title,body,labels",
  ]);

  if (proc.exitCode !== 0) {
    log.die(`Failed to fetch issue #${issueNum}. Check repo name and issue number.`);
  }

  const json = JSON.parse(proc.stdout.toString());

  return {
    title: json.title,
    body: json.body || "No description provided.",
    labels: json.labels?.map((l: { name: string }) => l.name).join(", ") || "none",
  };
}

export async function pushAndCreatePR(
  repo: string,
  worktreeDir: string,
  branchName: string,
  defaultBranch: string,
  issueNum: string,
  issue: Issue
) {
  // Check for unpushed commits or uncommitted changes
  const unpushed = Bun.spawnSync(["git", "log", `origin/${defaultBranch}..HEAD`, "--oneline"], { cwd: worktreeDir });
  const diffCheck = Bun.spawnSync(["git", "diff", "--quiet"], { cwd: worktreeDir });
  const cachedCheck = Bun.spawnSync(["git", "diff", "--cached", "--quiet"], { cwd: worktreeDir });

  const hasUnpushed = unpushed.stdout.toString().trim().length > 0;
  const hasUncommitted = diffCheck.exitCode !== 0 || cachedCheck.exitCode !== 0;

  if (!hasUnpushed && !hasUncommitted) {
    log.warn("No changes detected. Claude may not have made any modifications.");
    log.warn(`Worktree: ${worktreeDir}`);
    return;
  }

  // Stage any unstaged changes Claude might have left
  if (hasUncommitted) {
    log.info("Staging uncommitted changes...");
    Bun.spawnSync(["git", "add", "-A"], { cwd: worktreeDir });
    Bun.spawnSync(["git", "commit", "-m", `fix: address issue #${issueNum} - ${issue.title}`], { cwd: worktreeDir });
  }

  // Push
  log.info(`Pushing branch '${branchName}' to origin...`);
  const push = Bun.spawnSync(["git", "push", "-u", "origin", branchName], { cwd: worktreeDir });
  if (push.exitCode !== 0) {
    log.die("Failed to push. Check your git credentials.");
  }
  log.ok("Branch pushed.");

  // Create PR
  log.info("Opening pull request...");

  const prBody = `## Summary

Closes #${issueNum}

This PR was generated by [mog](https://github.com/workingdevshero/mog) using Claude Code in a Docker sandbox.

### Issue: ${issue.title}

${issue.body}

---
*Please review the changes carefully before merging.*`;

  const prTitle = `fix: ${issue.title} [#${issueNum}]`;

  const pr = Bun.spawnSync([
    "gh", "pr", "create",
    "--repo", repo,
    "--base", defaultBranch,
    "--head", branchName,
    "--title", prTitle,
    "--body", prBody,
  ], { cwd: worktreeDir });

  if (pr.exitCode !== 0) {
    log.die("Failed to create PR. You may need to push first or the PR may already exist.");
  }

  const prUrl = pr.stdout.toString().trim();
  log.ok("Pull request created!");
  console.log(`\x1b[0;32m${prUrl}\x1b[0m`);

  console.log();
  log.ok(`All done! Issue #${issueNum} → Branch '${branchName}' → PR opened.`);
  log.info(`Worktree: ${worktreeDir}`);
  log.info(`To clean up the worktree later: git worktree remove ${worktreeDir}`);
}
